spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: employee-info
          uri: lb://EMPLOYEE-INFO
          predicates:
            - Path=/employee/**
          filters:
            - JwtAuthFilter

        - id: department-info
          uri: lb://DEPARTMENT-INFO
          predicates:
            - Path=/department/**
          filters:
            - JwtAuthFilter

        - id: address-info
          uri: lb://ADDRESS-INFO
          predicates:
            - Path=/address/**
          filters:
            - JwtAuthFilter
        
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

server:
  port: 7777
