spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: employee-info
          uri: lb://EMPLOYEE-INFO
          predicates:
            - Path=/employee/**
        - id: department-info
          uri: lb://DEPARTMENT-INFO
          predicates:
            - Path=/department/**
        - id: address-info
          uri: lb://ADDRESS-INFO
          predicates:
            - Path=/address/**
  
server:
  port: 7777

# Okta OAuth2 Configuration
okta:
  oauth2:
    issuer: https://dev-98542581.okta.com/oauth2/default
    audience: api://default
    client-id: 0oanwp3vluL35pCWE5d7
    client-secret: kri3JQRqmWSRPtsWCOCth7QczK2YcFEkPJOhooFPAiLM0vqKVJ1_bbu5wJ7itscJ
    scopes: openid, profile, email, offline_access
    issuer-uri: https://dev-98542581.okta.com/oauth2/default
