spring:
  application:
    name: cloud-gateway
  config:
    import: "optional:configserver:http://localhost:9999"
  cloud:
    gateway:
      routes:
        - id: employee-info
          uri: lb://EMPLOYEE-INFO
          predicates:
            - Path=/employee/**
        - id: department-info
          uri: lb://DEPARTMENT-INFO
          predicates:
            - Path=/department/**
        - id: address-info
          uri: lb://ADDRESS-INFO
          predicates:
            - Path=/address/**

server: 
  port: 7777
