spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: employee-info
          uri: https://employee-microservice-example.onrender.com
          predicates:
            - Path=/employee/**
          filters:
            - JwtAuthFilter

        - id: department-info
          uri: https://department-microservice-example.onrender.com
          predicates:
            - Path=/department/**
          filters:
            - JwtAuthFilter

        - id: address-info
          uri: https://address-microservice-example.onrender.com
          predicates:
            - Path=/address/**
          filters:
            - JwtAuthFilter
        
        - id: auth-service
          uri: https://auth-service-example.onrender.com
          predicates:
            - Path=/auth/**

server:
  port: 8080
