spring:
  cloud:
    gateway:
      routes:
        - id: employee-info
          uri: lb://EMPLOYEE-INFO
          predicates:
            - Path=/employee/**
        - id: department-info
          uri: lb://DEPARTMENT-INFO
          predicates:
            - Path=/department/**