server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:5432/postgres
    username: postgres.gmeqjfecykahhgyrukca
    password: Patel@123Yash
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: INFO
    com.example: DEBUG  
  file:
    name: logs/application.log 
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n" 
