server:
  port: 9999

spring:
  application:
    name: cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Yash-123patel/microservice-example-configuration
          clone-on-start: true
          default-label: main
