spring:
  application:
    name: employee-info
  config:
    import: optional:configserver:http://localhost:9999
  r2dbc:
    url: 

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      departmentBreaker:
        registerHealthIndicator: true
        event-consumer-buffer-size: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 3   # Reduced to trigger faster
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  retry:
    instances:
      departmentRetry:
        max-attempts: 2
        wait-duration: 500ms  

  ratelimiter:
    instances:
      userRateLimiter:
        limit-refresh-period: 10s   
        limit-for-period: 3     
        timeout-duration: 0s
